add_rules("mode.debug", "mode.release")
add_requires("minhook")

target("poly")
    set_languages("c++23")
    set_kind("shared")
    add_files("src/*.cpp")
    add_files("src/renderer/**.cpp")
    add_files("src/imgui/**.cpp")
    add_files("src/imgui/TextEditor/**.cpp")
    add_includedirs("src")
    add_syslinks("winhttp", "user32", "d3d11", "dxgi")
    add_packages("minhook")
